version: '2.1'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: betest
    volumes:
      - ./my-data:/var/lib/mysql  

  app:
    build: ./
    image: converter-server
    restart: always
    depends_on:
      - db 
    links:
      - db
    ports :
      - "8080:8080"
